-- AlterTable
ALTER TABLE "RosterEntry" ADD COLUMN "mvUp" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "RosterEntry" ADD COLUMN "stUp" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "RosterEntry" ADD COLUMN "agUp" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "RosterEntry" ADD COLUMN "paUp" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "RosterEntry" ADD COLUMN "avUp" INTEGER NOT NULL DEFAULT 0;
